import os

SAMPLE_RATE = 16000
N_MFCC = 13
FRAME_LENGTH_MS = 25
HOP_LENGTH_MS = 10
INCLUDE_DELTAS = True
TOTAL_FEATURES = N_MFCC * 3 if INCLUDE_DELTAS else N_MFCC

N_COMPONENTS = 32
COVARIANCE_TYPE = 'diag'
REG_COVAR = 1e-6
MAX_ITER_GMM = 100

TIMIT_DATASET_FOLDER_ON_DISK = '/path/to/your/timit/data'

BASE_OUTPUT_DIR = 'Voice_Biometrics_TIMIT_GMM'
GMM_MODEL_FOLDER_NAME = 'GMM_Models'
FEATURE_FOLDER_NAME = 'Features'

MODEL_DIR = os.path.join(BASE_OUTPUT_DIR, GMM_MODEL_FOLDER_NAME)
FEATURE_DIR = os.path.join(BASE_OUTPUT_DIR, FEATURE_FOLDER_NAME)

VERIFICATION_THRESHOLD = -20.0